services:
  bot:
    build: . 
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /bot


  db: 
    image: postgres
    container_name: db_bot_container
    volumes:
      - db_bot_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: db_bot
    ports:
          - 5432:5432


volumes:
  db_bot_data:
